### ISSUE TITLE
Hi how do I download and use the module?

### ISSUE THREAD

**Issue by realflow100** [pparent76/ML_video_av#1]
Hi how do I download and use the module? I dont know how to compile anything myself. I just want to use the module and try it out.

theres no releases I can find and download links on magic lantern forum are broken

**Comment by pparent76** [comment]
Here is how to do:

1- Donwload the code here https://foss.heptapod.net/magic-lantern/magic-lantern/
2- Apply the patch lens.diff
3- Add video_av folder in modules directory
4- Build ( https://magiclantern.fandom.com/wiki/Build_instructions/Unified#Compiling_Magic_Lantern_.2F_Unified )

**Comment by pparent76** [comment]
Sorry I do not have any old archive anymore? What is your camera model?

**Comment by realflow100** [comment]
Canon 500D rebel T1i

Compiling something is waaaaaay beyond my skill level. I have no idea how to even begin doing any of that. theres sooo many endless instructions and dependencies and things required to be already pre-set-up and i dont know how to do any of that D:

**Comment by pparent76** [comment]
I don't have an image for 500D sorry. And I don't have a 500D device anymore and the time to compile it for it sorry.

Besides, this module works best on 550D. It can do things on 500D but it won't be as fluid.

See on magic lantern forum if someone can help you with it.

**Comment by pparent76** [comment]
Ha you're lucky I just found an old archive I compiled before: 

for 500D:
https://www.own-mailbox.com/magiclantern-Nightly.2017Dec10.500D111.zip

For 550D:
https://www.own-mailbox.com/magiclantern-Nightly.2017Dec12.550D109.zip

Try at your own risks, I could not test it again. Do not hesitate to tell me and others, if it works.

**Comment by realflow100** [comment]
Okay I'll see how it goes if it works or bricks my camera. Hopefully the former rather than the later!

**Comment by realflow100** [comment]
So far seems like it works. but I'm constantly having to tap the half-shutter button! even with 30 minute delay thing active. Would sticky half-shutter give me good results? Also its pretty slow to adapt to exposure level. but at least it works.
I find I need at least a threshold of 10 at least to not have it flashing in brightness. but it seems sluggish to adapt to exposure level at that setting. not sure what I should be doing.

**Comment by realflow100** [comment]
it crashed randomly a few seconds after i started recording video doesnt always happen. no clue why. just random crash detected out of nowhere.

Something about assert sound device?

**Comment by pparent76** [comment]
Did you disable ML global draw,disable energy saving, use a fully charged battery, and not overload vidéo bitrate?

On 550D it's very reliable, I use it very often on production to make videos.

**Comment by realflow100** [comment]
Yas I have done all of those things except global draw because I want magic zoom for fine-tuning manual focus 
and I'm using a wired AC Adapter during the test instead of battery. 
because this thing eats batteries like candy lol

Autofocus is useless in video mode. takes forever and hunts like crazy for up to 10 seconds sometimes. and sometimes even just gives up completely.

**Comment by pparent76** [comment]
Well anyway I use this thing only for still shots, and fixed focus (I set the right focus, before starting to shoot). Beyond that use case, I don't think 500D or 550D can produce good quality footage. (Manual focus adjustment during shooting, except if you're an expert, will usually not look that good on image, because of hesitations).

Global drawing, and especially magic zoom, really creates a lot of problems with this module, because it eats up a lot of CPU, and this module needs CPU as well to be efficient.

**Comment by pparent76** [comment]
By the way, when available one good configuration, is to disable smooth changes in video_av module, but to enable ML "gradual exposure" feature in video menu. That's my config on 550D but I think to recall that feature did not exist in 500D.

Also to remove glitches I made this tool: https://github.com/pparent76/noglitch

**Comment by realflow100** [comment]
oh ok my 500D doesnt have that

I just bought a canon SL1 which has moderately better autofocusing in video. its continuous at least. not the best like dual pixel but its better than nothing. and some other features. already got magic lantern installed for additional features too.
